spring.application.name=practice

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


mybatis.type-aliases-package=com.finalproject.practice.**.dto
mybatis.configuration.map-underscore-to-camel-case=true
